DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
	PRICE_LIST IDENTITY PRIMARY KEY,
	BRAND_ID INT4 NOT NULL,
	PRODUCT_ID INT4 NOT NULL,
	PRIORITY INT4 NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRICE NUMERIC(16, 2) NOT NULL,
	CURR TEXT NOT NULL
);